/**
 * Domain vocabulary for Lord Battle Tactics (AD-4: the engine owns these
 * types; no app redeclares them). Wording follows the PRD Glossary verbatim:
 * a **match** is one full loop draft → placement → reveal → battle → result;
 * a **battle** is the automated combat between the two revealed boards,
 * made of one **engagement** (MVP mode) or several (until-wipeout mode);
 * an engagement resolves in **passes** on the AGI initiative timeline, each
 * unit spending **actions**. New domain words go to the PRD Glossary first.
 */

/** The six unit classes (FR1, FR15). RPS triangle: mage > knight > archer > mage (FR14). */
export type UnitClass = 'knight' | 'mercenary' | 'archer' | 'mage' | 'cleric' | 'witch';

/**
 * The four elements (FR3), rolled per unit at draft from the owner's element
 * stream. A Witch's prepared spell is keyed to her element (FR16); for every
 * other class the element is cosmetic in the MVP.
 */
export type Element = 'fire' | 'water' | 'wind' | 'earth';

/**
 * The two sides of a battle (AD-11). The engine knows only 'A' and 'B';
 * in vs-AI play the human is always side 'A'.
 */
export type Side = 'A' | 'B';

/**
 * Grid rows, owner-local (AD-11): 'front' is the row nearest the enemy from
 * the owner's own perspective. Lane mirroring is renderer math, never data.
 */
export type Row = 'front' | 'mid' | 'back';

/**
 * Grid columns, owner-local (AD-11), from the owner's own perspective.
 * A unit's **facing column** is the enemy column directly across its lane;
 * its **reach** is that column plus adjacent ones (FR7).
 */
export type Col = 'left' | 'center' | 'right';

/** Battle mode (FR17, FR19): one engagement, or engagements until wipeout. */
export type Mode = 'single' | 'wipeout';

/**
 * The Witch's four spells, keyed to her element (FR16):
 * water→sleep, earth→poison, fire→weaken, wind→confusion.
 * The mapping itself lives in the balance data.
 */
export type SpellKind = 'sleep' | 'poison' | 'weaken' | 'confusion';

/**
 * Unit identity: `side:index`, assigned by the engine from the order of
 * `MatchSetup.armies` (AD-11). Display names and sprites are shell-side.
 */
export type UnitId = `${Side}:${number}`;

/** One drafted unit: a class plus its rolled element (FR1, FR3). */
export interface Unit {
  class: UnitClass;
  element: Element;
}

/** One cell of the owner's 3×3 grid (FR4), owner-local coordinates (AD-11). */
export interface Placement {
  row: Row;
  col: Col;
}

/**
 * The canonical battle input, exactly as AD-9 fixes it. A battle is a pure
 * function of this object (FR20): same `MatchSetup` → bit-identical battle.
 *
 * - `seed` — the single 32-bit unsigned **seed** all randomness derives from
 *   (AD-10 named streams); generated by the shell, fresh per match.
 * - `balanceVersion` — must match the engine's balance data version (AD-8).
 * - `armies` — both drafted armies; elements are **stored data**, rolled once
 *   at draft via the engine's roll function, never re-derived (AD-9).
 * - `placements` — parallel-indexed to `armies` (unit index → grid cell),
 *   owner-local (AD-11).
 */
export interface MatchSetup {
  seed: number;
  balanceVersion: number;
  mode: Mode;
  armies: { A: Unit[]; B: Unit[] };
  placements: { A: Placement[]; B: Placement[] };
}
